%% Test QR decoding
% http://www.mathworks.com/matlabcentral/fileexchange/29239-qr-code-encode-
% and-decode
% by Lior Shapira 2010Nov
% edited by Matt Pepper 2012Nov

% WARNING SUPPRESSION ***************************************************
%this first warning warns the user that: there is a "core.jar" is
%already specified on static java path. Seeing as we don't use other java
%functions, we shouldn't have any conflict respecifying core.jar
s = warning('off','MATLAB:javaclasspath:jarAlreadySpecified');

%These javaaddpath cmds are the cause the suppressed warnings above and
%should point to the folder where you installed ZXing
javaaddpath('C:\Program Files\zxing-2.0\core\core.jar');
javaaddpath('C:\Program Files\zxing-2.0\javase\javase.jar');

%this second warning indicates an: Out of range value converted to
%intmin('uint8') or intmax('uint8'). This seems to be just a nanny alarm
%generated by decode_qr
r = warning('off','MATLAB:intConvertOverflow');

% CODE SECTION **********************************************************
% In this section, we will capture an image using the HP webcam and Matlab
% Image Acquisition Toolbox, then process it using decode_qr

test_encode = captureVideoFrame(10,2);

% Decode the QR code
message = decode_qr(test_encode)

%reinitialize the warnings that were turned off above
warning(s);
warning(r);